# Generated by Django 5.1.5 on 2026-05-15 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0002_seed_aec_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Owning tenant. Null only during initial migration backfill.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tenants.tenant'),
        ),
    ]
