# Generated by Django 5.1.5 on 2026-05-15 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_backfill_aec_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictDCRReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('movie_title', models.CharField(max_length=255)),
                ('screen_name', models.CharField(max_length=100)),
                ('show_time', models.TimeField(blank=True, null=True)),
                ('raw_pdf', models.FileField(blank=True, null=True, upload_to='dcr_pdfs/%Y/%m/')),
                ('parser_version', models.CharField(default='1.0', max_length=50)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('raw_text_dump', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PARSED', 'Parsed'), ('VALIDATED', 'Validated'), ('VARIANCE_FOUND', 'Variance Found'), ('APPROVED', 'Approved'), ('POSTED', 'Posted')], default='PARSED', max_length=20)),
                ('parsed_gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('parsed_gst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parsed_etax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parsed_cess', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parsed_nett_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('parsed_distributor_share', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('parsed_exhibitor_share', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('computed_gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('computed_nett_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('computed_distributor_share', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('computed_exhibitor_share', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('distributor_share_percentage', models.DecimalField(decimal_places=2, default=50.0, help_text='Expected share ratio e.g., 50.0', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dcr_reports', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dcr_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DCRTicketClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_class_name', models.CharField(max_length=100)),
                ('ticket_count', models.PositiveIntegerField(default=0)),
                ('ticket_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('parsed_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_classes', to='integrations.districtdcrreport')),
            ],
        ),
        migrations.CreateModel(
            name='DCRDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discrepancy_type', models.CharField(choices=[('GROSS_MISMATCH', 'Gross Mismatch'), ('TAX_MISMATCH', 'Tax Mismatch'), ('NETT_MISMATCH', 'Nett Mismatch'), ('SPLIT_MISMATCH', 'Split Mismatch'), ('MISSING_FIELDS', 'Missing Fields')], max_length=50)),
                ('description', models.TextField()),
                ('variance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='integrations.districtdcrreport')),
            ],
        ),
    ]
