# Generated by Django 5.1.5 on 2026-05-18 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_dcr_models'),
        ('tenants', '0004_seed_aec_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_name', models.CharField(choices=[('DISTRICT', 'District DCR'), ('BOOKMYSHOW', 'BookMyShow Ticketing'), ('PETPOOJA', 'Petpooja POS'), ('HR_APP', 'External HR App'), ('TEAMS', 'Microsoft Teams Alerts'), ('PERPLEXITY', 'Perplexity AI Analytics')], max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Healthy'), ('INACTIVE', 'Inactive'), ('ERROR', 'Error'), ('SYNCING', 'Syncing'), ('PAUSED', 'Paused')], default='INACTIVE', max_length=15)),
                ('auth_type', models.CharField(choices=[('API_KEY', 'API Key'), ('OAUTH2', 'OAuth 2.0'), ('BEARER_TOKEN', 'Bearer Token'), ('BASIC', 'Basic Auth'), ('CREDENTIALS', 'Username / Password')], default='API_KEY', max_length=20)),
                ('sync_frequency', models.CharField(choices=[('REAL_TIME', 'Real-time'), ('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MANUAL', 'Manual')], default='DAILY', max_length=15)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('test_conn_result', models.TextField(blank=True, verbose_name='Test Connection Result')),
                ('credentials_json', models.JSONField(blank=True, default=dict, help_text='Store API keys, URLs, and token info securely')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activation Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connectors', to='tenants.tenant')),
            ],
            options={
                'ordering': ['connector_name'],
                'unique_together': {('tenant', 'connector_name')},
            },
        ),
    ]
