# Generated by Django 5.1.5 on 2026-05-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_integrationconnector'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtdcrreport',
            name='mismatch_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='districtdcrreport',
            name='parsed_occupancy',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Parsed occupancy percentage or count', max_digits=10),
        ),
        migrations.AddField(
            model_name='districtdcrreport',
            name='posting_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('FILM_FINANCE_PUSHED', 'Film Finance Pushed')], default='DRAFT', max_length=30),
        ),
        migrations.AddField(
            model_name='districtdcrreport',
            name='raw_archive_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='districtdcrreport',
            name='reprocess_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='districtdcrreport',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='districtdcrreport',
            name='reviewer_note',
            field=models.TextField(blank=True),
        ),
    ]
