# Generated by Django 6.0.5 on 2026-05-19 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_districtdcrreport_mismatch_flag_and_more'),
        ('revenue', '0012_advertiser_adcampaign'),
        ('tenants', '0004_seed_aec_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetpoojaSalesBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField()),
                ('bill_datetime', models.DateTimeField()),
                ('bill_number', models.CharField(max_length=100)),
                ('external_order_id', models.CharField(max_length=100)),
                ('shift', models.CharField(blank=True, max_length=50)),
                ('counter', models.CharField(blank=True, max_length=100)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_mode', models.CharField(blank=True, max_length=100)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('sync_timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_imported_to_aec', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petpooja_bills', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'external_order_id')},
            },
        ),
        migrations.CreateModel(
            name='PetpoojaSalesLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('external_item_id', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='integrations.petpoojasalesbill')),
            ],
        ),
        migrations.CreateModel(
            name='PetpoojaSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('ITEM_SYNC', 'Item Sync'), ('SALES_SYNC', 'Sales Sync')], max_length=20)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial Success')], default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petpooja_sync_jobs', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PetpoojaFailedSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('record_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('error_reason', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.petpoojasyncjob')),
            ],
        ),
        migrations.CreateModel(
            name='PetpoojaItemMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_item_id', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_rule', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('is_mapped', models.BooleanField(default=False)),
                ('aec_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petpooja_mappings', to='revenue.canteenitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petpooja_item_maps', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'external_item_id')},
            },
        ),
    ]
