# Generated by Django 6.0.5 on 2026-05-19 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_petpoojasalesbill_petpoojasaleslineitem_and_more'),
        ('tenants', '0004_seed_aec_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='districtdcrreport',
            name='parsed_convenience_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='districtdcrreport',
            name='parsed_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='districtdcrreport',
            name='parsed_settlement_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='districtdcrreport',
            name='show_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='districtdcrreport',
            name='source_platform',
            field=models.CharField(default='District', max_length=50),
        ),
        migrations.CreateModel(
            name='DistrictImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(upload_to='district_imports/')),
                ('source_file_name', models.CharField(max_length=255)),
                ('source_file_type', models.CharField(max_length=50)),
                ('source_period', models.CharField(blank=True, max_length=100)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('parser_template', models.CharField(default='default_v1', max_length=100)),
                ('parse_status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PARSING', 'Parsing'), ('PARSED_SUCCESS', 'Parsed Success'), ('PARSED_PARTIAL', 'Parsed Partial'), ('FAILED', 'Failed')], default='UPLOADED', max_length=30)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('review_status', models.CharField(default='PENDING', max_length=30)),
                ('approval_status', models.CharField(default='PENDING', max_length=30)),
                ('reprocess_count', models.IntegerField(default=0)),
                ('raw_archive_ref', models.CharField(blank=True, max_length=500)),
                ('audit_reference', models.CharField(blank=True, max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_timestamp'],
            },
        ),
        migrations.AddField(
            model_name='districtdcrreport',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parsed_rows', to='integrations.districtimportjob'),
        ),
    ]
