# Generated by Django 5.1.5 on 2026-05-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_districtdcrreport_parsed_convenience_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtdcrreport',
            name='posting_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('FILM_FINANCE_PUSHED', 'Distributor Finance Pushed')], default='DRAFT', max_length=30),
        ),
    ]
