# Generated by Django 5.2.5 on 2026-05-01 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_name', models.CharField(max_length=200)),
                ('gross_collection', models.DecimalField(decimal_places=2, max_digits=12)),
                ('share_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('share_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('week_number', models.PositiveSmallIntegerField(default=1, help_text='Week of release (share % varies)')),
                ('is_settled', models.BooleanField(default=False)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributor_shares', to='screens.show')),
            ],
            options={
                'ordering': ['-show__show_date'],
            },
        ),
        migrations.CreateModel(
            name='FilmAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_name', models.CharField(max_length=200)),
                ('advance_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('release_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='screens.movie')),
                ('screen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='screens.screen')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
    ]
