# Generated by Django 5.1.5 on 2026-05-15 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('tenants', '0002_seed_aec_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorshare',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributor_shares', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='filmadvance',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='film_advances', to='tenants.tenant'),
        ),
    ]
