# Generated by Django 5.1.5 on 2026-05-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_distributorshare_distributor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='attached_document',
            field=models.FileField(blank=True, null=True, upload_to='finance/distributors/documents/'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='bank_details_reference',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='default_settlement_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='default_share_logic',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='gst_id',
            field=models.CharField(blank=True, help_text='GST/Tax ID', max_length=50),
        ),
        migrations.AddField(
            model_name='distributor',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
