# Generated by Django 5.1.5 on 2026-05-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_distributor_address_distributor_attached_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmcontract',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='filmcontract',
            name='contract_attachment',
            field=models.FileField(blank=True, null=True, upload_to='finance/contracts/'),
        ),
        migrations.AddField(
            model_name='filmcontract',
            name='holdback_rule',
            field=models.TextField(blank=True, help_text='e.g. 10% held until final DCR'),
        ),
        migrations.AddField(
            model_name='filmcontract',
            name='mg_recovery_logic',
            field=models.TextField(blank=True, help_text='e.g. Recovered from Week 1 net'),
        ),
        migrations.AddField(
            model_name='filmcontract',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='filmcontract',
            name='revenue_share_rule',
            field=models.TextField(blank=True, help_text='e.g. Week 1: 50%, Week 2: 40%'),
        ),
        migrations.AddField(
            model_name='filmcontract',
            name='settlement_frequency',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly'), ('MONTHLY', 'Monthly'), ('END_OF_RUN', 'End of Run')], default='WEEKLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='filmcontract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SETTLED', 'Settled'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
