# Generated by Django 5.1.5 on 2026-05-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_filmcontract_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='approval_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='mg_recouped',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='settlement',
            name='other_adjustments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='settlement',
            name='total_nett',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='settlement',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='status',
            field=models.CharField(choices=[('GENERATED', 'Generated'), ('VALIDATED', 'Validated'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='GENERATED', max_length=20),
        ),
    ]
