# Generated by Django 5.1.5 on 2026-05-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_settlement_approval_timestamp_settlement_mg_recouped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorstatement',
            name='movies_included',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='distributorstatement',
            name='net_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='distributorstatement',
            name='sent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributorstatement',
            name='settlements',
            field=models.ManyToManyField(blank=True, related_name='statements', to='finance.settlement'),
        ),
        migrations.AddField(
            model_name='distributorstatement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='distributorstatement',
            name='total_adjustments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='distributorstatement',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='distributorstatement',
            name='total_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='distributorstatement',
            name='total_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
