# Generated by Django 5.1.5 on 2026-05-18 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_seed_aec_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone_code', models.CharField(max_length=20)),
                ('capacity_2w', models.PositiveIntegerField(default=0, help_text='Total 2-wheeler slots')),
                ('capacity_4w', models.PositiveIntegerField(default=0, help_text='Total 4-wheeler slots')),
                ('is_overflow', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_zones', to='tenants.tenant')),
            ],
            options={
                'ordering': ['zone_code'],
                'unique_together': {('tenant', 'zone_code')},
            },
        ),
        migrations.CreateModel(
            name='ParkingSlotEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('show_slot', models.CharField(choices=[('MORNING', 'Morning (10:00–13:00)'), ('AFTERNOON', 'Afternoon (13:00–16:00)'), ('EVENING', 'Evening (16:00–19:00)'), ('NIGHT', 'Night (19:00–22:00)'), ('LATE_NIGHT', 'Late Night (22:00+)')], max_length=15)),
                ('tw_opening', models.PositiveIntegerField(default=0, verbose_name='2W Opening Count')),
                ('tw_entered', models.PositiveIntegerField(default=0, verbose_name='2W Entered')),
                ('tw_exited', models.PositiveIntegerField(default=0, verbose_name='2W Exited')),
                ('tw_closing', models.PositiveIntegerField(default=0, editable=False, verbose_name='2W Closing')),
                ('fw_opening', models.PositiveIntegerField(default=0, verbose_name='4W Opening Count')),
                ('fw_entered', models.PositiveIntegerField(default=0, verbose_name='4W Entered')),
                ('fw_exited', models.PositiveIntegerField(default=0, verbose_name='4W Exited')),
                ('fw_closing', models.PositiveIntegerField(default=0, editable=False, verbose_name='4W Closing')),
                ('overflow_used', models.BooleanField(default=False)),
                ('special_day_tag', models.CharField(choices=[('NONE', 'Normal Day'), ('WEEKEND', 'Weekend'), ('HOLIDAY', 'Public Holiday'), ('FESTIVAL', 'Festival'), ('EVENT', 'Special Event')], default='NONE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_entries_entered', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_entries', to='tenants.tenant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_entries_verified', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='parking.parkingzone')),
            ],
            options={
                'ordering': ['-date', 'show_slot'],
                'unique_together': {('tenant', 'zone', 'date', 'show_slot')},
            },
        ),
    ]
