# Generated by Django 5.1.5 on 2026-05-15 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-safe identifier, used for subdomain routing.', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('timezone', models.CharField(default='Asia/Kolkata', help_text='IANA timezone string, e.g. Asia/Kolkata', max_length=50)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('working_days_per_month', models.PositiveSmallIntegerField(default=26, help_text='Standard working days used for payroll proration.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(help_text='e.g. CAFE, LAMP_REGISTRY, FINANCE, ADVERTISING', max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Module-specific configuration overrides.')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Module',
                'verbose_name_plural': 'Tenant Modules',
                'unique_together': {('tenant', 'module_key')},
            },
        ),
    ]
