# Generated by Django 5.1.5 on 2026-05-15 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0002_priceversion'),
        ('tenants', '0002_seed_aec_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='screen',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='screens', to='tenants.tenant'),
        ),
    ]
