# Generated by Django 5.1.5 on 2026-05-15 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0003_add_tenant_fk'),
        ('tenants', '0003_backfill_aec_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='screen_type',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX'), ('4DX', '4DX'), ('OTHER', 'Other')], default='2D', max_length=10),
        ),
        migrations.AddField(
            model_name='seatcategory',
            name='seat_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seatcategory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seat_categories', to='tenants.tenant'),
        ),
    ]
