# Generated by Django 5.1.5 on 2026-05-18 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0004_screen_type_and_seat_category_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='screens.seatcategory'),
        ),
    ]
