# Generated by Django 5.1.5 on 2026-05-18 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0005_alter_seat_category'),
        ('tenants', '0004_seed_aec_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateField()),
                ('show_slot', models.CharField(help_text='e.g. Morning, Matinee, Evening, Night', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft / Planned'), ('PUBLISHED', 'Published / Live'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('conflict_flag', models.BooleanField(default=False, verbose_name='Conflict Flag')),
                ('conflict_details', models.TextField(blank=True)),
                ('holiday_override', models.BooleanField(default=False, verbose_name='Holiday Override')),
                ('schedule_history', models.JSONField(blank=True, default=list, verbose_name='Schedule History')),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_schedules', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='screens.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='screens.screen')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='show_schedules', to='tenants.tenant')),
            ],
            options={
                'ordering': ['show_date', 'start_time'],
            },
        ),
    ]
