# Generated by Django 5.1.5 on 2026-05-18 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_refactor_global_to_tenant'),
        ('tenants', '0004_seed_aec_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Vendor Name')),
                ('category', models.CharField(choices=[('MAINTENANCE', 'Maintenance Services'), ('UTILITIES', 'Utility Provider'), ('CAFE', 'Cafe Purchases'), ('OPERATIONS', 'General Operations'), ('DISTRIBUTOR', 'Film Distributor'), ('EXPENSES', 'General Expenses'), ('OTHERS', 'Others')], default='OTHERS', max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gst_number', models.CharField(blank=True, max_length=15, verbose_name='GST Number')),
                ('address', models.TextField(blank=True)),
                ('default_payment_terms', models.CharField(blank=True, help_text='e.g. Net 30, COD, Net 15', max_length=100)),
                ('bank_details_ref', models.TextField(blank=True, help_text='Bank Account Number, IFSC, UPI info', verbose_name='Bank Details Reference')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
