# Generated by Django 5.1.5 on 2026-05-18 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_vendor'),
        ('tenants', '0004_seed_aec_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(help_text='e.g. Lamp Hours Life, Daily Diesel Burn', max_length=200)),
                ('module', models.CharField(help_text='e.g. OPERATIONS, GENERATOR, LAMPS, UTILITY', max_length=100)),
                ('threshold_value', models.DecimalField(decimal_places=2, help_text='Value that triggers warning/alert', max_digits=12)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='tenants.tenant')),
            ],
            options={
                'ordering': ['module', 'rule_name'],
            },
        ),
    ]
