# Generated by Django 5.1.5 on 2026-05-15 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_cafeexpense'),
        ('tenants', '0002_seed_aec_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisingslot',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ad_slots', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='cafeexpense',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cafe_expenses', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='canteensale',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canteen_sales', to='tenants.tenant'),
        ),
    ]
