# Generated by Django 5.1.5 on 2026-05-15 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0003_add_tenant_fk'),
        ('tenants', '0003_backfill_aec_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cafe_units', to='tenants.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='cafeexpense',
            name='cafe_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='revenue.cafeunit'),
        ),
        migrations.AddField(
            model_name='canteensale',
            name='cafe_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='revenue.cafeunit'),
        ),
    ]
