# Generated by Django 5.1.5 on 2026-05-18 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0005_seed_cafe_units'),
        ('tenants', '0004_seed_aec_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='canteenitem',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='canteenitem',
            name='is_track_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='canteenitem',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='canteenitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canteen_items', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='canteenitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average purchase cost', max_digits=8),
        ),
        migrations.AddField(
            model_name='canteensale',
            name='cogs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost of goods sold for margin logic', max_digits=10),
        ),
        migrations.AlterField(
            model_name='canteenitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price', max_digits=8),
        ),
        migrations.CreateModel(
            name='CafeInward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vendor_name', models.CharField(blank=True, help_text='Link to Vendor Master conceptually', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cafe_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='revenue.cafeunit')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inwards', to='revenue.canteenitem')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CafeWastage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cafe_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='revenue.cafeunit')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wastage_logs', to='revenue.canteenitem')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
