# Generated by Django 5.1.5 on 2026-05-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0006_canteenitem_current_stock_canteenitem_is_track_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteenitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='canteenitem',
            name='recipe_mapping',
            field=models.TextField(blank=True, help_text='Recipe/Consumption Mapping rules'),
        ),
        migrations.AddField(
            model_name='canteenitem',
            name='sku',
            field=models.CharField(blank=True, help_text='SKU/Item Code', max_length=50),
        ),
        migrations.AddField(
            model_name='canteenitem',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='canteenitem',
            name='tax_rule',
            field=models.CharField(blank=True, help_text='e.g., GST 5%', max_length=50),
        ),
        migrations.AddField(
            model_name='canteenitem',
            name='unit',
            field=models.CharField(default='PCS', help_text='e.g., PCS, KG, LTR', max_length=20),
        ),
    ]
