# Generated by Django 5.1.5 on 2026-05-18 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0007_canteenitem_notes_canteenitem_recipe_mapping_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeinward',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inwards_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cafeinward',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='revenue/inwards/bills/'),
        ),
        migrations.AddField(
            model_name='cafeinward',
            name='batch',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cafeinward',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cafeinward',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cafeinward',
            name='posting_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='cafeinward',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inwards_entered', to=settings.AUTH_USER_MODEL),
        ),
    ]
