# Generated by Django 5.1.5 on 2026-05-18 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0008_cafeinward_approved_by_cafeinward_attachment_and_more'),
        ('tenants', '0004_seed_aec_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeDailyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sold_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recipe_consumption_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('manual_adjustment_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('closing_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumptions_approved', to=settings.AUTH_USER_MODEL)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='revenue.canteenitem')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('tenant', 'date', 'item')},
            },
        ),
    ]
