# Generated by Django 5.1.5 on 2026-05-18 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0009_cafedailyconsumption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cafewastage',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wastage_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cafewastage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='revenue/wastage/proofs/'),
        ),
        migrations.AddField(
            model_name='cafewastage',
            name='category',
            field=models.CharField(choices=[('SPOILAGE', 'Spoilage/Damage'), ('EXPIRED', 'Expired'), ('INTERNAL_LOSS', 'Internal Loss')], default='SPOILAGE', max_length=50),
        ),
        migrations.AddField(
            model_name='cafewastage',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cafewastage',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='cafewastage',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wastage_entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cafewastage',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost Impact', max_digits=10),
        ),
    ]
