# Generated by Django 5.1.5 on 2026-05-18 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0010_cafewastage_approved_by_cafewastage_attachment_and_more'),
        ('tenants', '0004_seed_aec_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeReorderAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock_at_alert', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reorder_level_at_alert', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('suggested_reorder_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_purchase_date', models.DateField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SNOOZED', 'Snoozed'), ('ORDERED', 'Marked Ordered'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=20)),
                ('snooze_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reorder_alerts', to='revenue.canteenitem')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
