# Generated by Django 5.1.5 on 2026-05-18 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0011_cafereorderalert'),
        ('screens', '0006_showschedule'),
        ('tenants', '0004_seed_aec_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertisers', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=150)),
                ('ad_type', models.CharField(choices=[('SLIDES', 'On-screen Slides'), ('VIDEO_PROMO', 'Video Promo / Trailer'), ('BANNER', 'Physical Banner'), ('STANDEE', 'Canteen Standee'), ('COUNTER_AD', 'POS Counter Ad')], default='SLIDES', max_length=20)),
                ('campaign_start', models.DateField()),
                ('campaign_end', models.DateField()),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='revenue/ad_creatives/')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_status', models.CharField(choices=[('PLANNED', 'Planned'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('SUSPENDED', 'Suspended')], default='PLANNED', max_length=15)),
                ('billing_status', models.CharField(choices=[('UNBILLED', 'Unbilled'), ('INVOICED', 'Invoiced'), ('PAID', 'Paid'), ('WRITTEN_OFF', 'Written Off')], default='UNBILLED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screen_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='screens.screen')),
                ('show_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='screens.show')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='tenants.tenant')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='revenue.advertiser')),
            ],
            options={
                'ordering': ['-campaign_start'],
            },
        ),
    ]
