# Generated by Django 5.2.5 on 2026-05-01 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('screen_1_shows', models.PositiveSmallIntegerField(default=0)),
                ('screen_2_shows', models.PositiveSmallIntegerField(default=0)),
                ('tickets_sold', models.PositiveIntegerField(default=0)),
                ('initial_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_conversion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('elec_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('units_per_show', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('occupancy_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GeneratorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours_run', models.DecimalField(decimal_places=2, max_digits=5)),
                ('consumption', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('diesel_added', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('diesel_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('diesel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LampLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('working_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('closing_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lamp_logs', to='screens.screen')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('screen', 'date')},
            },
        ),
    ]
