# Generated by Django 5.2.5 on 2026-05-02 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('screens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LampInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField()),
                ('purchase_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rated_lifespan_hours', models.DecimalField(decimal_places=2, default=3000, max_digits=8)),
                ('installed_date', models.DateField(blank=True, null=True)),
                ('retired_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lamp_inventory', to='screens.screen')),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.AddField(
            model_name='lamplog',
            name='lamp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lamp_logs', to='operations.lampinventory'),
        ),
    ]
