# Generated by Django 5.1.5 on 2026-05-15 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_lampinventory_lamplog_lamp'),
        ('tenants', '0002_seed_aec_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricityreading',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='electricity_readings', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='generatorlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generator_logs', to='tenants.tenant'),
        ),
    ]
