# Generated by Django 5.1.5 on 2026-05-15 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_add_tenant_fk'),
        ('tenants', '0003_backfill_aec_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meter_type', models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('GENERATOR', 'Generator'), ('WATER', 'Water'), ('OTHER', 'Other')], max_length=20)),
                ('unit_label', models.CharField(help_text='e.g. kWh, Liters', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utility_meters', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='UtilityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('rate_per_unit', models.DecimalField(decimal_places=4, max_digits=10)),
                ('effective_from', models.DateField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='operations.utilitymeter')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='UtilityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('initial_reading', models.DecimalField(decimal_places=2, max_digits=12)),
                ('final_reading', models.DecimalField(decimal_places=2, max_digits=12)),
                ('consumption', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('billed_units', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='operations.utilitymeter')),
            ],
            options={
                'ordering': ['-reading_date'],
                'unique_together': {('meter', 'reading_date')},
            },
        ),
    ]
