# Generated by Django 5.1.5 on 2026-05-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_migrate_electricity_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilityreading',
            name='override_reason',
            field=models.TextField(blank=True, help_text='Required if initial reading differs from previous closing'),
        ),
    ]
