# Generated by Django 5.1.5 on 2026-05-15 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_utility_override_reason'),
        ('screens', '0003_add_tenant_fk'),
        ('tenants', '0003_backfill_aec_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='e.g. LAMP, PROJECTOR, SOUND, DG_SET, METER', max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('tracks_hours', models.BooleanField(default=False)),
                ('tracks_fuel', models.BooleanField(default=False)),
                ('tracks_units', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
            },
        ),
        migrations.CreateModel(
            name='AssetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('rated_life_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('specs_json', models.JSONField(blank=True, default=dict)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='operations.assetcategory')),
            ],
        ),
        migrations.CreateModel(
            name='TenantAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('installed_date', models.DateField(blank=True, null=True)),
                ('current_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('alert_threshold_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('screen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='screens.screen')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='operations.assettemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AssetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('opening_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closing_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='operations.tenantasset')),
            ],
            options={
                'ordering': ['-log_date'],
            },
        ),
    ]
