# Generated by Django 5.1.5 on 2026-05-15 07:20

from django.db import migrations

def seed_and_migrate(apps, schema_editor):
    AssetCategory = apps.get_model('operations', 'AssetCategory')
    AssetTemplate = apps.get_model('operations', 'AssetTemplate')
    TenantAsset = apps.get_model('operations', 'TenantAsset')
    AssetLog = apps.get_model('operations', 'AssetLog')
    
    LampInventory = apps.get_model('operations', 'LampInventory')
    LampLog = apps.get_model('operations', 'LampLog')
    Tenant = apps.get_model('tenants', 'Tenant')

    # Seed Categories
    lamp_cat, _ = AssetCategory.objects.get_or_create(key='LAMP', defaults={'label': 'Projection Lamp', 'tracks_hours': True})
    AssetCategory.objects.get_or_create(key='PROJECTOR', defaults={'label': 'Digital Projector', 'tracks_hours': True})
    AssetCategory.objects.get_or_create(key='SOUND', defaults={'label': 'Sound Processor', 'tracks_hours': False})
    AssetCategory.objects.get_or_create(key='DG_SET', defaults={'label': 'Generator', 'tracks_hours': True, 'tracks_fuel': True})
    AssetCategory.objects.get_or_create(key='METER', defaults={'label': 'Utility Meter', 'tracks_units': True})

    # Find AEC Tenant
    aec_tenant = Tenant.objects.filter(slug='aec-cinemas').first()
    if not aec_tenant:
        return

    # Migrate Lamps
    for old_lamp in LampInventory.objects.all():
        # Create or find a template
        manufacturer = old_lamp.manufacturer or 'Unknown'
        model_num = old_lamp.model_number or 'Unknown'
        
        template, _ = AssetTemplate.objects.get_or_create(
            category=lamp_cat,
            manufacturer=manufacturer,
            model_number=model_num,
            defaults={'rated_life_hours': old_lamp.rated_lifespan_hours}
        )

        # Create TenantAsset
        new_asset = TenantAsset.objects.create(
            tenant=aec_tenant,
            template=template,
            screen=old_lamp.screen,
            serial_number=old_lamp.serial_number,
            installed_date=old_lamp.installed_date,
            is_active=old_lamp.is_current,
            alert_threshold_hours=100.0, # default alert threshold
        )

        # Migrate Logs
        for old_log in old_lamp.lamp_logs.all():
            AssetLog.objects.create(
                asset=new_asset,
                log_date=old_log.date,
                opening_value=old_log.opening_hours,
                closing_value=old_log.closing_hours,
                delta=old_log.working_hours,
                entered_by=old_log.entered_by,
                created_at=old_log.created_at
            )
        
        # Calculate current hours
        from django.db.models import Sum
        total_hours = new_asset.logs.aggregate(total=Sum('delta'))['total'] or 0
        new_asset.current_hours = total_hours
        new_asset.save()


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_universal_asset_registry'),
        ('tenants', '0003_backfill_aec_tenant'),
    ]

    operations = [
        migrations.RunPython(seed_and_migrate, reverse_code=migrations.RunPython.noop),
    ]
