# Generated by Django 5.1.5 on 2026-05-18 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_seed_and_migrate_assets'),
        ('tenants', '0004_seed_aec_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_contact', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('contract_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('coverage_details', models.TextField(blank=True, help_text='What is covered under this AMC')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRING', 'Expiring Soon'), ('EXPIRED', 'Expired'), ('RENEWED', 'Renewed')], default='ACTIVE', max_length=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='maintenance/amc/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assets', models.ManyToManyField(blank=True, related_name='amc_contracts', to='operations.tenantasset')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amc_contracts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['end_date'],
            },
        ),
        migrations.CreateModel(
            name='FaultTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=15)),
                ('reported_date', models.DateField()),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, help_text='Technician / Vendor name', max_length=200)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='maintenance/faults/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fault_tickets', to='operations.tenantasset')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fault_tickets_reported', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fault_tickets', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-reported_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PMSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half-Yearly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom (Hours)')], max_length=15)),
                ('interval_hours', models.DecimalField(blank=True, decimal_places=2, help_text='For CUSTOM frequency', max_digits=8, null=True)),
                ('last_done_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField()),
                ('assigned_to', models.CharField(blank=True, max_length=200)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pm_schedules', to='operations.tenantasset')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pm_schedules', to='tenants.tenant')),
            ],
            options={
                'ordering': ['next_due_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_number', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('CORRECTIVE', 'Corrective (Fault)'), ('PREVENTIVE', 'Preventive (PM)'), ('INSPECTION', 'Inspection')], default='CORRECTIVE', max_length=15)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=15)),
                ('assigned_to', models.CharField(blank=True, max_length=200)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='maintenance/work_orders/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='operations.tenantasset')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fault_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='operations.faultticket')),
                ('pm_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='operations.pmschedule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
