# Generated by Django 5.1.5 on 2026-05-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_amccontract_faultticket_pmschedule_workorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultticket',
            name='category',
            field=models.CharField(choices=[('ELECTRICAL', 'Electrical'), ('MECHANICAL', 'Mechanical'), ('HVAC', 'HVAC / Air Conditioning'), ('AV', 'Audio / Visual'), ('PROJECTION', 'Projection'), ('PLUMBING', 'Plumbing'), ('CIVIL', 'Civil / Structural'), ('IT', 'IT / Networking'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='faultticket',
            name='closure_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faultticket',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Repair cost', max_digits=10),
        ),
        migrations.AddField(
            model_name='faultticket',
            name='downtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='faultticket',
            name='escalation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faultticket',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faultticket',
            name='reported_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faultticket',
            name='resolution_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faultticket',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='faultticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=15),
        ),
    ]
