# Generated by Django 5.1.5 on 2026-05-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_faultticket_category_faultticket_closure_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmschedule',
            name='checklist',
            field=models.JSONField(blank=True, default=list, help_text='List of checklist items as JSON array'),
        ),
        migrations.AddField(
            model_name='pmschedule',
            name='completed_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of times this PM has been completed'),
        ),
        migrations.AddField(
            model_name='pmschedule',
            name='maintenance_type',
            field=models.CharField(choices=[('INSPECTION', 'Inspection'), ('LUBRICATION', 'Lubrication'), ('CALIBRATION', 'Calibration'), ('CLEANING', 'Cleaning'), ('REPLACEMENT', 'Parts Replacement'), ('TESTING', 'Testing & Verification'), ('FULL_SERVICE', 'Full Service'), ('OTHER', 'Other')], default='INSPECTION', max_length=20),
        ),
        migrations.AddField(
            model_name='pmschedule',
            name='reminder_lead_days',
            field=models.PositiveIntegerField(default=3, help_text='Days before due to send reminder alert'),
        ),
        migrations.AddField(
            model_name='pmschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pmschedule',
            name='assigned_to',
            field=models.CharField(blank=True, help_text='Vendor / Technician name', max_length=200),
        ),
    ]
