# Generated by Django 5.1.5 on 2026-05-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_pmschedule_checklist_pmschedule_completed_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='assigned_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='parts_used',
            field=models.TextField(blank=True, help_text='Comma-separated or freetext parts list'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='scope_of_work',
            field=models.TextField(blank=True, help_text='Detailed scope / instructions for the technician'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='vendor_invoice',
            field=models.FileField(blank=True, null=True, upload_to='maintenance/invoices/'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='vendor_invoice_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='actual_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Any additional miscellaneous cost', max_digits=10),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='assigned_to',
            field=models.CharField(blank=True, help_text='Vendor / Technician name', max_length=200),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=15),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='wo_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
