# Generated by Django 5.1.5 on 2026-05-18 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_workorder_assigned_timestamp_workorder_parts_used_and_more'),
        ('tenants', '0004_seed_aec_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_type', models.CharField(choices=[('CORRECTIVE', 'Corrective Repair'), ('PREVENTIVE', 'Preventive Maintenance'), ('INSPECTION', 'Inspection'), ('WARRANTY', 'Warranty Service'), ('AMC', 'AMC Service')], default='CORRECTIVE', max_length=15)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('downtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='maintenance/service_history/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amc_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_history', to='operations.amccontract')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_history', to='operations.tenantasset')),
                ('fault_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_history', to='operations.faultticket')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_history', to='tenants.tenant')),
                ('work_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_record', to='operations.workorder')),
            ],
            options={
                'verbose_name_plural': 'Service History',
                'ordering': ['-service_date', '-created_at'],
            },
        ),
    ]
