# Generated by Django 5.1.5 on 2026-05-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_servicehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='amccontract',
            name='coverage_type',
            field=models.CharField(choices=[('AMC_COMPREHENSIVE', 'AMC – Comprehensive'), ('AMC_NON_COMP', 'AMC – Non-Comprehensive'), ('WARRANTY_OEM', 'OEM Warranty'), ('WARRANTY_EXTENDED', 'Extended Warranty'), ('SERVICE_CONTRACT', 'Annual Service Contract')], default='AMC_COMPREHENSIVE', max_length=25),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='renewal_history',
            field=models.JSONField(blank=True, default=list, help_text='Auto-appended log of renewal events'),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='renewal_status',
            field=models.CharField(choices=[('NOT_INITIATED', 'Not Initiated'), ('IN_PROGRESS', 'Renewal In Progress'), ('RENEWED', 'Renewed'), ('NOT_RENEWING', 'Not Renewing')], default='NOT_INITIATED', max_length=15),
        ),
        migrations.AddField(
            model_name='amccontract',
            name='warranty_end_date',
            field=models.DateField(blank=True, help_text='OEM warranty expiry (may differ from AMC)', null=True),
        ),
        migrations.AlterField(
            model_name='amccontract',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='maintenance/amc/agreements/'),
        ),
        migrations.AlterField(
            model_name='amccontract',
            name='coverage_details',
            field=models.TextField(blank=True, help_text='What is covered under this contract'),
        ),
        migrations.AlterField(
            model_name='amccontract',
            name='end_date',
            field=models.DateField(help_text='AMC / contract end date'),
        ),
        migrations.AlterField(
            model_name='amccontract',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRING', 'Expiring Soon'), ('EXPIRED', 'Expired'), ('RENEWED', 'Renewed'), ('LAPSED', 'Lapsed')], default='ACTIVE', max_length=15),
        ),
        migrations.AlterField(
            model_name='amccontract',
            name='vendor_contact',
            field=models.CharField(blank=True, help_text='Support contact name / phone / email', max_length=200),
        ),
    ]
