# Generated by Django 5.1.5 on 2026-05-18 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_amccontract_coverage_type_and_more'),
        ('tenants', '0004_seed_aec_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_reading', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_reading', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('consumption', models.DecimalField(decimal_places=2, default=0, help_text='Metered consumption (calculated: closing - opening)', max_digits=12)),
                ('tanker_purchase_qty', models.DecimalField(decimal_places=2, default=0, help_text='Tanker purchase quantity (in Liters)', max_digits=12)),
                ('tanker_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('municipal_bill', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='maintenance/water_logs/')),
                ('linked_vendor', models.CharField(blank=True, max_length=200)),
                ('expense_ref', models.CharField(blank=True, help_text='Linked expense entry code/ID', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter', models.ForeignKey(limit_choices_to={'meter_type': 'WATER'}, on_delete=django.db.models.deletion.PROTECT, related_name='water_logs', to='operations.utilitymeter')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='water_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
