# Generated by Django 5.1.5 on 2026-05-18 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_waterlog'),
        ('tenants', '0004_seed_aec_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('LAMP_THRESHOLD', 'Lamp Threshold'), ('ASSET_PM_DUE', 'Asset Maintenance Due'), ('UTILITY_ANOMALY', 'Utility Anomaly'), ('DCR_MISMATCH', 'DCR Mismatch'), ('SETTLEMENT_OVERDUE', 'Settlement Overdue'), ('PARKING_OVERFLOW', 'Parking Overflow'), ('PENDING_APPROVAL', 'Pending Approval'), ('GENERATOR_VARIANCE', 'Generator Variance'), ('HR_SYNC_FAILURE', 'HR Sync Failure')], max_length=30)),
                ('source_module', models.CharField(help_text='e.g. Revenue, Screens, Maintenance, Utilities', max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=15)),
                ('triggered_time', models.DateTimeField(auto_now_add=True)),
                ('reference_record', models.CharField(blank=True, help_text='Reference table and primary key e.g. BookingCorrection-4', max_length=150)),
                ('status', models.CharField(choices=[('TRIGGERED', 'Triggered'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('SNOOZED', 'Snoozed')], default='TRIGGERED', max_length=15)),
                ('resolution_note', models.TextField(blank=True)),
                ('audit_ref', models.CharField(blank=True, max_length=50, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operational_alerts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-triggered_time'],
            },
        ),
    ]
