# Generated by Django 5.1.5 on 2026-05-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_operationalalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilityreading',
            name='anomaly_status',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('ANOMALY', 'Critical Anomaly')], default='NORMAL', max_length=20, verbose_name='Anomaly Status'),
        ),
        migrations.AddField(
            model_name='utilityreading',
            name='bill_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Bill Amount'),
        ),
        migrations.AddField(
            model_name='utilityreading',
            name='bill_attachment',
            field=models.FileField(blank=True, null=True, upload_to='utilities/bills/', verbose_name='Bill Attachment'),
        ),
        migrations.AddField(
            model_name='utilityreading',
            name='closing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='utilityreading',
            name='opening',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='utilityreading',
            name='posting_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='DRAFT', max_length=20, verbose_name='Posting Status'),
        ),
        migrations.AddField(
            model_name='utilityreading',
            name='review_note',
            field=models.TextField(blank=True, verbose_name='Review Note'),
        ),
        migrations.AddField(
            model_name='utilityreading',
            name='trend_variance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage variance compared to baseline daily consumption', max_digits=8),
        ),
        migrations.AddField(
            model_name='utilityreading',
            name='utility_type',
            field=models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('WATER', 'Water'), ('GENERATOR', 'Generator'), ('OTHER', 'Other')], default='ELECTRICITY', max_length=20),
        ),
        migrations.AlterField(
            model_name='utilityreading',
            name='final_reading',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Backwards compatible alias for closing', max_digits=12),
        ),
        migrations.AlterField(
            model_name='utilityreading',
            name='initial_reading',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Backwards compatible alias for opening', max_digits=12),
        ),
        migrations.AlterField(
            model_name='utilityreading',
            name='override_reason',
            field=models.TextField(blank=True, help_text='Required if opening reading differs from previous closing'),
        ),
    ]
