# Generated by Django 5.1.5 on 2026-05-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_utilityreading_anomaly_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatorlog',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='generators/attachments/'),
        ),
        migrations.AddField(
            model_name='generatorlog',
            name='closing_diesel_stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Diesel stock level at end of day (opening + refill - consumed)', max_digits=10),
        ),
        migrations.AddField(
            model_name='generatorlog',
            name='closing_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='generatorlog',
            name='consumed_qty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Diesel consumed in liters', max_digits=10),
        ),
        migrations.AddField(
            model_name='generatorlog',
            name='opening_diesel_stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Diesel stock level at start of day', max_digits=10),
        ),
        migrations.AddField(
            model_name='generatorlog',
            name='opening_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='generatorlog',
            name='outage_tag',
            field=models.CharField(blank=True, help_text='Grid outage code/tag reference', max_length=150),
        ),
        migrations.AddField(
            model_name='generatorlog',
            name='refill_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='generatorlog',
            name='refill_qty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Refilled diesel quantity in liters', max_digits=10),
        ),
        migrations.AddField(
            model_name='generatorlog',
            name='refill_vendor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='generatorlog',
            name='runtime',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated running hours (closing - opening)', max_digits=8),
        ),
        migrations.AddField(
            model_name='generatorlog',
            name='variance_status',
            field=models.CharField(choices=[('NORMAL', 'Normal Burn'), ('HIGH_BURN', 'Abnormal High Burn'), ('LOW_BURN', 'Abnormal Low Burn')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='generatorlog',
            name='consumption',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Backwards compatible alias for consumed_qty', max_digits=8),
        ),
        migrations.AlterField(
            model_name='generatorlog',
            name='diesel_added',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Backwards compatible alias for refill_qty', max_digits=8),
        ),
        migrations.AlterField(
            model_name='generatorlog',
            name='hours_run',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Backwards compatible alias for runtime', max_digits=5),
        ),
    ]
