# Generated by Django 5.1.5 on 2026-05-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_generatorlog_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lampinventory',
            name='archived_flag',
            field=models.BooleanField(default=False, verbose_name='Archived Flag'),
        ),
        migrations.AddField(
            model_name='lampinventory',
            name='balance_life',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=10, verbose_name='Balance Life'),
        ),
        migrations.AddField(
            model_name='lampinventory',
            name='closing_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Closing Hours'),
        ),
        migrations.AddField(
            model_name='lampinventory',
            name='lamp_type',
            field=models.CharField(choices=[('XENON', 'Xenon'), ('LASER', 'Laser'), ('METAL_HALIDE', 'Metal Halide'), ('LED', 'LED')], default='XENON', max_length=20, verbose_name='Lamp Type'),
        ),
        migrations.AddField(
            model_name='lampinventory',
            name='opening_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Opening Hours'),
        ),
        migrations.AddField(
            model_name='lampinventory',
            name='status',
            field=models.CharField(choices=[('INSTALLED', 'Installed'), ('RUNNING', 'Running'), ('REPLACED', 'Replaced'), ('ARCHIVED', 'Archived')], default='INSTALLED', max_length=20),
        ),
        migrations.AddField(
            model_name='lampinventory',
            name='threshold',
            field=models.DecimalField(decimal_places=2, default=200, help_text='Warning threshold in hours', max_digits=8),
        ),
        migrations.AddField(
            model_name='lampinventory',
            name='vendor',
            field=models.CharField(blank=True, max_length=150, verbose_name='Vendor'),
        ),
        migrations.AddField(
            model_name='lampinventory',
            name='working_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Working Hours'),
        ),
        migrations.AlterField(
            model_name='lampinventory',
            name='installed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Install Date'),
        ),
        migrations.AlterField(
            model_name='lampinventory',
            name='retired_date',
            field=models.DateField(blank=True, null=True, verbose_name='Replacement Date'),
        ),
        migrations.AlterField(
            model_name='lampinventory',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Lamp ID'),
        ),
    ]
