# Generated by Django 5.1.5 on 2026-05-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_lampinventory_archived_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantasset',
            name='asset_id',
            field=models.CharField(blank=True, help_text='Unique Canonical Asset ID', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='tenantasset',
            name='asset_name',
            field=models.CharField(default='', max_length=150, verbose_name='Asset Name'),
        ),
        migrations.AddField(
            model_name='tenantasset',
            name='location',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='tenantasset',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenantasset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase Date'),
        ),
        migrations.AddField(
            model_name='tenantasset',
            name='service_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Service Due Date'),
        ),
        migrations.AddField(
            model_name='tenantasset',
            name='status',
            field=models.CharField(choices=[('OPERATIONAL', 'Operational'), ('OUT_OF_SERVICE', 'Out of Service'), ('MAINTENANCE', 'Under Maintenance'), ('RETIRED', 'Retired')], default='OPERATIONAL', max_length=30),
        ),
        migrations.AddField(
            model_name='tenantasset',
            name='vendor',
            field=models.CharField(blank=True, max_length=150, verbose_name='Vendor'),
        ),
        migrations.AddField(
            model_name='tenantasset',
            name='warranty',
            field=models.CharField(blank=True, max_length=200, verbose_name='Warranty'),
        ),
        migrations.AlterField(
            model_name='tenantasset',
            name='serial_number',
            field=models.CharField(default='', max_length=100, verbose_name='Serial No'),
        ),
    ]
