# Generated by Django 5.1.5 on 2026-05-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_tenantasset_asset_id_tenantasset_asset_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricityreading',
            name='working_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
