# Generated by Django 5.1.5 on 2026-05-15 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_add_tenant_fk'),
        ('tenants', '0004_seed_aec_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='after_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changelog',
            name='before_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changelog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_logs', to='tenants.tenant'),
        ),
    ]
