# Generated by Django 5.1.5 on 2026-05-18 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_enhance_changelog'),
        ('tenants', '0004_seed_aec_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditShieldLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(help_text='e.g. Movies, Settings, HR, Alert Center, Generator, Lamps, DCR', max_length=100)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('action_type', models.CharField(max_length=50)),
                ('old_value', models.JSONField(blank=True, default=dict, null=True)),
                ('new_value', models.JSONField(blank=True, default=dict, null=True)),
                ('approval_status', models.CharField(blank=True, default='', max_length=50)),
                ('alert_status', models.CharField(blank=True, default='', max_length=50)),
                ('sync_ref', models.CharField(blank=True, default='', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_shield_logs', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_shield_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
