# Generated by Django 5.1.5 on 2026-05-18 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('tenants', '0004_seed_aec_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction_type', models.CharField(choices=[('REFUND', 'Refund'), ('CANCELLATION', 'Cancellation'), ('COMPLIMENTARY', 'Complimentary Pass'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('original_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('audit_ref', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_mode', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Credit/Debit Card'), ('UPI', 'UPI'), ('WALLET', 'Digital Wallet'), ('NETBANKING', 'Net Banking'), ('NONE', 'None / Not Applicable')], default='NONE', max_length=20)),
                ('before_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('after_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adjustment_logic', models.TextField(blank=True, help_text='Explanation of manual adjustment logic')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_corrections', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='bookings.booking')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_corrections', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
