# Generated by Django 5.1.5 on 2026-05-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_aiinsightreport_aiactionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinsightreport',
            name='module',
            field=models.CharField(choices=[('EXECUTIVE', 'Executive Suite'), ('MOVIES', 'Movies'), ('BOOKINGS', 'Bookings'), ('REFUNDS', 'Refunds & Adjustments'), ('CAFE', 'Cafe Sales'), ('INVENTORY', 'Inventory Management'), ('ADVERTISING', 'Advertising'), ('UTILITY', 'Utility Readings'), ('WATER', 'Water Log'), ('GENERATOR', 'Generator'), ('LAMPS', 'Projection Lamps'), ('ASSETS', 'Asset Registry'), ('MAINTENANCE', 'Maintenance Desk'), ('PARKING', 'Parking Analytics'), ('FINANCE', 'Distributor Finance'), ('DCR', 'District DCR'), ('EXPENSE', 'Expense Register'), ('STAFF', 'Staff Report / HR Sync'), ('PNL', 'P&L Reports'), ('ALERTS', 'Alert Center'), ('AUDIT', 'Audit Shield')], max_length=50),
        ),
    ]
