# Generated by Django 5.1.5 on 2026-05-18 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        ('tenants', '0004_seed_aec_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='HRSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_time', models.DateTimeField(auto_now_add=True)),
                ('source_system', models.CharField(default='External HR API', max_length=100)),
                ('records_received', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('last_successful_sync', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('sync_status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial Success'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='SUCCESS', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hr_sync_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-sync_time'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='PRESENT', help_text='e.g. Present, Absent, Half-day, Late', max_length=30)),
                ('exception_flag', models.BooleanField(default=False, help_text='True if there is an anomaly (e.g. missed check-out)')),
                ('exception_note', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='payroll.staff')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date', 'staff__name'],
                'unique_together': {('staff', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ShiftMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_exception', models.BooleanField(default=False, help_text='Unscheduled shift or double shift alert')),
                ('exception_note', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_records', to='payroll.staff')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_records', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date', 'staff__name'],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
