# Generated by Django 5.1.5 on 2026-05-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_staff_tenant_hrsynclog_attendancemirror_shiftmirror'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='attendance_status',
            field=models.CharField(blank=True, default='PRESENT', help_text="Today's Attendance Status", max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Operational notes or exceptions'),
        ),
        migrations.AddField(
            model_name='staff',
            name='payroll_status',
            field=models.CharField(blank=True, default='READY', help_text='Payroll Readiness Status', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='shift',
            field=models.CharField(blank=True, default='Morning', help_text='Current Scheduled Shift', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='supervisor',
            field=models.CharField(blank=True, default='', help_text='Direct Supervisor Name', max_length=150),
        ),
        migrations.AddField(
            model_name='staff',
            name='sync_status',
            field=models.CharField(blank=True, default='SYNCED', help_text='HR System Sync Status', max_length=50),
        ),
    ]
